# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fb7f8a080af2e917a5b137dfa4b237a75c1015731d5f53c0d0d08f6d75650092f62e1cb686500d5262d522b5436ec4434a63deddd4ccea25dd641c625b87189a

test:
  secret_key_base: 5d44550daab58a10a1bd7253f54a85e2b7f6560b7329d02c383629d92e63906f911a82bf30b4b74066984d89e91046f16d216a6ae6ec18c50db917981afa9167

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
